vich_uploader:
    db_driver: orm

    mappings:
        projects_images:
            uri_prefix: '%project_images_path%'
            upload_destination: '%kernel.project_dir%/public%project_images_path%'
        projects_animations:
            uri_prefix: '%project_animations_path%'
            upload_destination: '%kernel.project_dir%/public%project_animations_path%'
